language: r
cache: packages

env:
  global:
    - secure: "ZSywuKwomB0QU3rTTpd+9fi2xQQ3B8x8hhNpg4oGKeUbvlRV8BUHTECsvNbnbt/yLUL3gKkmZJ9MNF9oScK+PIF8mxAekgtmEP2OWj9mOgNkHp/UI4zSNLw16gu5Ey8LUZDvLq1czg8CaxfjIQO9haLIeEQC0mCLD3JpCsn8ptmy/arB545vIqQ7ErP2CcPUfQu9WOEXpemM7uYquIXaVDN0M3UzMawHg3HlkE4rVpS+9Zkk3WunjGVupm14SyKAnPzQhyL6tUPqaosGNl83RUZGdoXE09HbGuxKrmgOnfzkNutewTiXnHxjzdIKahAA4QiKcXuRmQeo+oTZ7hoMzFuKeE/avoLpiWZCv4ZEKrTSYv4VSEDbde3u/WnIhFmnwpunkmMgg6ZQN+yI59gluzHJR4fyukMoAGaF/YGE+Z9jjF9q2g+pFNoOswzhcrO9YzqzbjyHorthpwqKgIkNGc4mojOlBouHUbl9wr6R73d38u/Q1qkG9opURkjYkEmIZtsvjqX/hM2fSyspjgmceU95dcCnIoLW3qCpx3siNRFdXv6T9F1RQtdXNOub+gejl0sQ7JsL9m1wPMp7IwkZajm1kD/v/Zuj2y2+PfXQbhGEky9iRbcOekQ47Ry5zwZtpSp5/pxr9CfXkQO/A935KJadAZvLnLVKqdSuAabs/OI="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

