language: r

env:
  global:
    - secure: ZfuXB6sPvMMY4pst4j4NGY1rsN3ZwxG75OLnMsx9w8F+FuCoKYYuIyKN76F2IWBqDE1zX3Ze254ho1j2ABBTjYxuyZhcqg5CyVrJbS9U1b5PCMCxXtDJxzy4TBefeEJf8TvrXDHUGz8W0B+bfiQNwtRMoj4u+eA6jMR7Jm93u5cWZfiuGnLeFSKozzTAQmMhbvwZlfsEFIBx7zxotNzxZuoa2DjMALge+y8DodDznw6dLCH+iKGkMPYJNYCtDEKXDo/0JzGsYi8oR7zyqgHpFLLjwUOANlZMBWbINXeS49RRrBlGMlXjRdKdUVPhdMClhAr+ameGlpPi/F57u+36IGgC8mp6RcRX7IWNqMpadREC6zezx1PfmEfqWZjvn/OHs9viECMEz9gTBdJjPB7Wz5IWULA8Y4MJMjkynKavkjVJzy+2XQIvnziY9mPwGk+kNG38H09l3elSrH52CLatRigl2n8+//UPJAPvv2a1itGAnDrHom8cww60NffvUPbrzeyTGEH21G9ZefbhML45cttGqk0+ObgGYlE4PWcMVr4lPSLmkaHoydeUPO+Rk0kKzHIxqEh2iHLMyH9cPpdu+CRr1hj65GtmtuqyHsj30MEPZ91HImhWKqtOwxAqTFnPW19/1BuSNkgyIe84s+U9vxOBzqmRTpxkOOi0H1ca9ng=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

