language: r

env:
  global:
    - secure: GyXnBGegAcK1voJZxZAsvRoS+tjd8K/jy8pHOAZ59vU80HjFUijDHIs5A7RoIwkGQw2H1q883JkmyvLBHuPKms6O8TRW5qWhG9DCawm67Mp1IDLbWmbduYri4xWOoPSwPZG4uOcjjmDAZWIxeHXlLYy80BcenNw/nagZiSSlKtgbNS270Kh8kGUIBdIpHTd75gR3uzIAgx++ugaCKgVjWOn2BDQ1zEhb0wXKtExvE1IPfXWYhGuU+GylBSgUtyF+GfJyU6ANR6H+A1xrJ9Thw5CwSZgOONI3XWwj3r9ftoi4diN71u5r8s2UyzJU+Q9PGDwlf6OY4RxR0GO2SdhiF/Q6pE+dA0fyi7YCLC6jMYlpXKYvzrxvJvE7etLi7Hm9K+DubNkbq6O9UHRTDSBBk8UbSlATeBLV2QMHvMD7ISSKl30Q4smOGggbAFBGmTE0m80xu1mk3HUOiumI9rdhyNIl95nzKiU9742n39TxkeCFfyPHhwupEA+NUZ7u3zJTuZALJcYlyJ5Z63LL1JJhrei+ei8Xc3QfUkoX5MTuPPA8dU2LoWn1iCFh3OuMsiIG8bs9oTXYqYUXgmQv3IaBuO5ChYWdVnl4JrFYYVUcZgbyUmT+x6tAT8tVnXCwgVGzQbnMZTMEcKZsT2cB4BAL1nX+ejdHjIZg75MiPNGeG8Y=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

